### ISSUE TITLE
create first time walkthrough intro

### ISSUE THREAD

**Issue by l00mi** [zazuko/www.alod.ch#36]
possible frameworks:
- http://introjs.com/
- https://github.com/heelhook/chardin.js

**Comment by l00mi** [comment]
lets go with http://github.hubspot.com/shepherd/ best to capsulate in a plugin which does introspect which features are available.

**Comment by StrubT** [comment]
created new branch zack-search/feature-intro
@l00mi please review

**Comment by l00mi** [comment]
@StrubT 
You did a great job in understanding (fast) the structure of the project and creating the new plugin!
(In general if you do this and see there was no documentation, please just go ahead and write down in a README.md some sentences which would have helped you to start. We notoriously had never enough time for this up to now.)

Now unfortunately on my set-up I get the following error, I did not investigate in detail.
```
shepherd.js:732 Uncaught TypeError: this.trigger is not a function
    at HTMLAnchorElement.start (shepherd.js:732)
start @ shepherd.js:732
```

Further I understood that sheperd.js meanwhile seems to be dead too. So I am considering to switch as we did not yet invest too much time yet. (Sorry about that!)

I looked at http://bootstraptour.com/ probably you find something even better?

How much time do you think does it take to switch over to another tour engine?

**Comment by StrubT** [comment]
@l00mi I will have a look into it. But I really like the backdrop / highlighting feature. It should not take too long to switch over. I will look into it Thursday or Friday and get back to you.

**Comment by StrubT** [comment]
I actually did manage to find some other frameworks, but each has its own quirks, so I ended up with the one you suggested.
* https://introjs.com/ -- looks good, unclear licencing
* http://iamdanfox.github.io/anno.js/ -- great, reaaaaaaly outdated
* http://bootstraptour.com/ -- looks good, works with standalone or bundled bootstrap

It took me a while to realise zack-search already uses a native bootstrap variant.
I had to include the 'regular' bootstrap instead because bootstrap-tour explicitly depends on jQuery.
@l00mi if this is not acceptable for you, we may have to choose yet another framework...

cannot reference from commit, so 1e26a719e344dce00839fc358110b2d8462f32e5

**Comment by StrubT** [comment]
@l00mi @bergos Thank you for moving the code from *zack-search* to *www.alod.ch*.
However, I have three questions.

1. Why did you copy `intro.js` and others, but not remove them from *zack-search*?

1. Did you also experience the problem that when loading the site for the first time, the tour did not start?
   You should be able to reproduce this problem by removing the stored state.
   I did some digging and noticed that they actually use `restart()` on their own page instead of `start()`, so I did the same.

1. @l00mi mentioned that the tour should automatically start when someone visits the site for the first time. Shall I implement that?

*removing stored state:*
`['tour_current_step','tour_end'].forEach(n => localStorage.removeItem(n))`

**Comment by bergos** [comment]
1. I asked in the chat for feedback. If it works for you, I will remove `intro.js` in zack-search.
2. Didn't noticed, but could be. I mainly tested if it's still working after my changes and for sure loaded the page multiple times before I pressed the tour button.
3. If there is an easy solution, I would prefer some visual highlighting of the question mark. (Can we shake it, like a pupil which likes to be choosen first by the teacher?)

**Comment by l00mi** [comment]
1. Yes please go ahead @bergos, I will take care of the queries and simple renderer.js
2. I had also some troubles. I actually would be like to start the tour, just that it might start on the ? itself.
3. see 2

**Comment by StrubT** [comment]
Sorry @l00mi, I don't get that.
